---
- hosts: all
  become: yes
  tasks:
    - name: Install packages
      apt: update_cache=yes name={{ item }} state=latest
      with_items:
        - apache2
        - python3
        - python3-pip
        - libapache2-mod-wsgi-py3
    - name: flask installation via pip
      pip: name=flask
- hosts: all
  become: yes
  tasks:
    - name: copy web-pages to var/www/
      copy:
        src: "var/www/"
        dest: "/var/www"
      notify:
        - Restart Apache
    - name: copy virtual host config
      copy:
        src: "config/000-default.conf"
        dest: "/etc/apache2/sites-available/000-default.conf"
      notify:
        - Restart Apache
    - name: Get a list of all vhosts
      find:
        paths: "/etc/apache2/sites-available"
        patterns: "*.conf"
        file_type: file
      register: find
    - name: Apply symlinks in sites-enabled
      file:
        dest: /etc/apache2/sites-enabled/{{ item.path | basename }}
        src: "{{ item.path }}"
        state: link
        force: yes
      with_items: "{{ find.files }}"
      notify:
        - Restart Apache
  handlers:
    - name: Restart Apache
      service: name=apache2 state=restarted
