name: CMake
 
on:
  push:
    branches: [ task-ci ]
  pull_request:
    branches: [ master ]
 
jobs:
  build:
    runs-on: ubuntu-latest
 
    steps:
    - uses: actions/checkout@v2
 
    - name: Build
      shell: bash
 
      working-directory: ${{github.workspace}}/task-ci
      
      run: |
        git clone https://github.com/google/googletest.git
        mv googletest 3rdparty
        mkdir build
        cd build
        cmake ..
        cmake --build .
 
    - name: Test
      uses: akhtyamovpavel/ActionGtestReport@v0.0.9
      env:
          GOOGLE_TEST_DIR: ${{github.workspace}}/task-ci/3rdparty
          Task4_SOURCE_DIR: ${{github.workspace}}/taskci
      with:
        exec-path:  ${{github.workspace}}/task-ci/bin/CTestExe
        report-path: "../report.xml"
        working-directory: ${{github.workspace}}/task-ci/bin/
 
    - name: UploadArtifacts
      uses: actions/upload-artifact@v2
      with:
        name: test-report
        path: ${{github.workspace}}/task-ci/report.xml
 
    - uses: actions/upload-artifact@v2
      with:
        name: Distributive
        path: |
          ${{github.workspace}}/task-ci/bin/
          ${{github.workspace}}/task-ci/lib/h
